### ISSUE TITLE
which project is good for pytorch for me 

### ISSUE THREAD

**Issue by ahkhalwai** [Polarbeargo/Secure-Private-AI-Facebook-Scholarship-KeyStone-project#1]
how i become good on that project? I required discussion, kernel , research paper to read ?

**Comment by polarbeargo** [comment]
You already find the best choice for you in your Day 4 Udacity's Intro to Deep Learning with PyTorch start from here and try your best learn the course notebook from [cezannec](https://github.com/cezannec/capsule_net_pytorch). Start follow her on GitHub and read her notebook relate to PyTorch. Remember to send a star to the great work you meet:)!
![1](https://user-images.githubusercontent.com/8589224/60397268-95ec0100-9b7d-11e9-93d9-3e55344d237c.png)

**Comment by polarbeargo** [comment]
@ahkhalwai And read the following three great references:
* https://arxiv.org/pdf/1607.00133.pdf
* https://github.com/Polarbeargo/private-ai/blob/master/Section_1_Differential_Privacy.ipynb
* https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf
* Play the following kernel as a hands-on project to have a better feeling about PyTorch It's mostly in our lesson 2 https://www.kaggle.com/abhinand05/in-depth-guide-to-convolutional-neural-networks

**Comment by ahkhalwai** [comment]
thank you so much Hsin, u so handsome girl with golden heart and respects a lot ur fans like me .. 

i want to learn how kaggle people work on competitions, by discussion, research paper, kernel etc

**Comment by ahkhalwai** [comment]
i will start this by tommorow , i want to start cs50 harvard today ... 
@Polarbeargo

**Comment by polarbeargo** [comment]
@ahkhalwai We are classmates. We are on this together, I am happy to have you!  This readme becomes colorful because you found me thanks to you.

**Comment by ahkhalwai** [comment]
thank you so much @Polarbeargo :+1:

**Comment by polarbeargo** [comment]
Prepare to meet the coolest people in the CS50 study group. You will meet a lot of interesting people and eventually find your path:)!

**Comment by ahkhalwai** [comment]
lets go ... @Polarbeargo still i love competitions so definitely I will find the way for kaggle competition ...
